### ISSUE TITLE
[BUG] Import - CSV with long column names - Unexpected column names generated

### ISSUE THREAD

**Issue by snlwih** [sassoftware/sas-studio-custom-steps#111]
**Describe the bug**
@nachorodriguez79 
Using a CSV file with long names where the first 32 characters are the same, seem to result in generated names like VAR3 instead of an abbreviated name for VAR3.
I realize this is an edge case, so no need to fix. But might be an idea to add a section "Known Issues" to the readme and list issue. 

**To Reproduce**
1. Use the custom step and read the attached CSV file
[CSV-with-really-long-column-names.csv](https://github.com/sassoftware/sas-studio-custom-steps/files/13752916/CSV-with-really-long-column-names.csv)

**Expected behavior**
All columns should have an abbreviated version of the A clear and concise description of what you expected to happen.

**Screenshots**
Here is a screenshot of the CSV file: 
![image](https://github.com/sassoftware/sas-studio-custom-steps/assets/35299890/428c9d2c-568b-414c-a225-4c75201ae364)

And a screenshot of the Preview Data tab for the output port of the step: 
![image](https://github.com/sassoftware/sas-studio-custom-steps/assets/35299890/4801b40f-bb0c-4cd4-a62e-3f1d0beca36b)

**Environment (please complete the following information):**
 - Name of custom step: Import - GCSFS File Reader/Import - GCSFS File Reader.step
 - SAS Viya version: 2023.12
 - Browser: Chrome

**Additional context**

**Comment by IgnacioRodriguezSanchez** [comment]
Added a know issues section in the README file with the following description:

- When the input file has long column names where the the first 32 characters are not unique, then the generated output table will have columns that are named VARx (x being the column number) for those columns.
- The label of those VARx columns will include the name of the original variable.
- This behaviour is caused by the use of proc import in this custom step. It might be possible to read the file using a data step, but that is something to consider for a future version of this step.

Besides, the about tab has been updated accordingly.

**Comment by snlwih** [comment]
Thanks. have merged your pull request https://github.com/sassoftware/sas-studio-custom-steps/pull/120 and will close as completed.
